name: FreeFire Mod Menu Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Theos
      run: |
        # Instalar ldid para firmar el binario
        brew install ldid
        rm -rf ~/theos
        export THEOS=~/theos
        git clone --recursive https://github.com/theos/theos.git $THEOS
        rm -rf $THEOS/sdks
        git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks

    - name: Build Tweak
      run: |
        export THEOS=~/theos
        # Buscar el directorio que contiene el Makefile
        MAKEFILE_DIR=$(find . -name Makefile -not -path "./theos/*" | head -n 1 | xargs dirname)
        echo "Cambiando al directorio: $MAKEFILE_DIR"
        cd "$MAKEFILE_DIR"
        make clean
        make package FINALPACKAGE=1
      env:
        THEOS: ~/theos

    - name: Upload DEB
      uses: actions/upload-artifact@v4
      with:
        name: FreeFire_ModMenu_DEB
        path: "**/packages/*.deb"
